package InterfaceControle;

import java.awt.Color;

public class JPainelAnimais extends javax.swing.JPanel {

    public JPainelAnimais() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbAdiar = new javax.swing.JButton();
        jlMensagem = new javax.swing.JLabel();
        jbResolver = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jbAdiar.setBackground(new java.awt.Color(255, 255, 255));
        jbAdiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/JPainel_adiar_todos.png"))); // NOI18N
        jbAdiar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbAdiarMouseMoved(evt);
            }
        });
        jbAdiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbAdiarMouseExited(evt);
            }
        });
        jbAdiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdiarActionPerformed(evt);
            }
        });

        jlMensagem.setText("total animais");

        jbResolver.setBackground(new java.awt.Color(255, 255, 255));
        jbResolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/JPainel_resolver_todos.png"))); // NOI18N
        jbResolver.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbResolverMouseMoved(evt);
            }
        });
        jbResolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbResolverMouseExited(evt);
            }
        });
        jbResolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbResolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(199, Short.MAX_VALUE)
                .addComponent(jbAdiar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addComponent(jbResolver, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(187, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jbAdiar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(89, Short.MAX_VALUE)
                    .addComponent(jbResolver, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(21, 21, 21)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbAdiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdiarActionPerformed
        jbAdiar.setEnabled(false);
        jbResolver.setEnabled(false);

    }//GEN-LAST:event_jbAdiarActionPerformed

    private void jbResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbResolverActionPerformed
        jbAdiar.setEnabled(false);
        jbResolver.setEnabled(false);
    }//GEN-LAST:event_jbResolverActionPerformed

    private void jbResolverMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbResolverMouseMoved
        jbResolver.setBorder(javax.swing.BorderFactory.createLineBorder(Color.BLACK)); 
        jbResolver.setToolTipText("Resolver");
    }//GEN-LAST:event_jbResolverMouseMoved

    private void jbAdiarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAdiarMouseMoved
        jbAdiar.setBorder(javax.swing.BorderFactory.createLineBorder(Color.BLACK));
        jbAdiar.setToolTipText("Adiar");
    }//GEN-LAST:event_jbAdiarMouseMoved

    private void jbResolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbResolverMouseExited
        jbResolver.setBorder(javax.swing.BorderFactory.createLineBorder(Color.WHITE));
    }//GEN-LAST:event_jbResolverMouseExited

    private void jbAdiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAdiarMouseExited
        jbAdiar.setBorder(javax.swing.BorderFactory.createLineBorder(Color.WHITE));
    }//GEN-LAST:event_jbAdiarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAdiar;
    private javax.swing.JButton jbResolver;
    public javax.swing.JLabel jlMensagem;
    // End of variables declaration//GEN-END:variables
}
