package InterfaceControle;

import java.awt.Component;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import static javax.swing.SwingConstants.CENTER;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import persistencia.conexao;

public class VendasAnimais extends javax.swing.JFrame {

    private int cod_fazenda;
    
    public VendasAnimais(int codFazenda) {
        cod_fazenda = codFazenda;
        
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }
    
    public VendasAnimais(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        compoTipoVenda = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboLote = new javax.swing.JComboBox<>();
        comboPasto = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pesquisa_Id = new javax.swing.JTextField();
        pesquisa_SegundaId = new javax.swing.JTextField();
        pesquisa_lote = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pesquisa_Idade = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        pesquisa_Sexo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pesquisa_ComboTipoAnimal = new javax.swing.JComboBox<>();
        BotaoPesquisa_Pesquisa = new javax.swing.JButton();
        pesquisa_comboPasto = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTReaisArroba = new javax.swing.JTextField();
        jTTotalArroba = new javax.swing.JTextField();
        jTReaisManejo = new javax.swing.JTextField();
        jTReaisTotal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTMediaArroba = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVendaAnimais = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaPesquisaAnimais = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jtTotalAnimais = new javax.swing.JTextField();
        jtAnimaisFemeas = new javax.swing.JTextField();
        jtAnimaisMachos = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jtAnimaisMortos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Venda de Animais");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        compoTipoVenda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Por lote", "Por Pasto", "Por Animais" }));
        compoTipoVenda.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                compoTipoVendaPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel1.setText("Tipo de Venda:");

        jLabel2.setText("Número do lote:");

        jLabel3.setText("Animais do Pasto:");

        comboLote.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar" }));
        comboLote.setEnabled(false);
        comboLote.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                comboLotePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        comboPasto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar" }));
        comboPasto.setEnabled(false);
        comboPasto.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                comboPastoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Venda por Animais --- Pesquisar:"));

        jLabel4.setText("Id:");

        jLabel5.setText("Segunda Id:");

        jLabel6.setText("Lote:");

        pesquisa_Id.setEnabled(false);
        pesquisa_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisa_IdActionPerformed(evt);
            }
        });

        pesquisa_SegundaId.setEnabled(false);

        pesquisa_lote.setEnabled(false);
        pesquisa_lote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisa_loteActionPerformed(evt);
            }
        });

        jLabel7.setText("Idade:");

        pesquisa_Idade.setEnabled(false);
        pesquisa_Idade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisa_IdadeActionPerformed(evt);
            }
        });

        jLabel8.setText("Sexo:");

        pesquisa_Sexo.setEnabled(false);

        jLabel9.setText("Pasto:");

        jLabel10.setText("Tipo Animal:");

        pesquisa_ComboTipoAnimal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar" }));
        pesquisa_ComboTipoAnimal.setEnabled(false);

        BotaoPesquisa_Pesquisa.setText("Pesquisar");
        BotaoPesquisa_Pesquisa.setEnabled(false);
        BotaoPesquisa_Pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoPesquisa_PesquisaActionPerformed(evt);
            }
        });

        pesquisa_comboPasto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar" }));
        pesquisa_comboPasto.setEnabled(false);
        pesquisa_comboPasto.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                pesquisa_comboPastoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pesquisa_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pesquisa_lote))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pesquisa_SegundaId)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesquisa_comboPasto, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pesquisa_Idade, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pesquisa_Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pesquisa_ComboTipoAnimal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoPesquisa_Pesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(pesquisa_Idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(pesquisa_ComboTipoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(pesquisa_Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(pesquisa_comboPasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(BotaoPesquisa_Pesquisa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(pesquisa_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(pesquisa_SegundaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addComponent(pesquisa_lote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Totais:"));

        jLabel15.setText("R$ Total:");

        jLabel16.setText("Média de @ por animal:");

        jTReaisArroba.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTReaisArrobaKeyReleased(evt);
            }
        });

        jTTotalArroba.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTTotalArrobaKeyReleased(evt);
            }
        });

        jTReaisManejo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTReaisManejoKeyReleased(evt);
            }
        });

        jTReaisTotal.setEnabled(false);
        jTReaisTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTReaisTotalActionPerformed(evt);
            }
        });

        jLabel12.setText("R$ @:");

        jLabel13.setText("Total de @:");

        jLabel14.setText("R$ Manejo:");

        jTMediaArroba.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTReaisManejo)
                    .addComponent(jTTotalArroba)
                    .addComponent(jTReaisArroba)
                    .addComponent(jTReaisTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTMediaArroba, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTReaisArroba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel16)
                    .addComponent(jTMediaArroba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTTotalArroba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTReaisManejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTReaisTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(compoTipoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboLote, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboPasto, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(compoTipoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(comboLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(comboPasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        tabelaVendaAnimais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Lote Compra", "Pasto", "Idade", "Sexo", "Tipo Animal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaVendaAnimais);
        if (tabelaVendaAnimais.getColumnModel().getColumnCount() > 0) {
            tabelaVendaAnimais.getColumnModel().getColumn(0).setPreferredWidth(85);
            tabelaVendaAnimais.getColumnModel().getColumn(1).setPreferredWidth(85);
            tabelaVendaAnimais.getColumnModel().getColumn(2).setPreferredWidth(85);
            tabelaVendaAnimais.getColumnModel().getColumn(3).setPreferredWidth(85);
            tabelaVendaAnimais.getColumnModel().getColumn(4).setPreferredWidth(85);
            tabelaVendaAnimais.getColumnModel().getColumn(5).setPreferredWidth(85);
        }

        tabelaPesquisaAnimais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Lote Compra", "Pasto", "Idade", "Sexo", "Tipo Aniamal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaPesquisaAnimais.setEnabled(false);
        jScrollPane2.setViewportView(tabelaPesquisaAnimais);
        if (tabelaPesquisaAnimais.getColumnModel().getColumnCount() > 0) {
            tabelaPesquisaAnimais.getColumnModel().getColumn(0).setPreferredWidth(85);
            tabelaPesquisaAnimais.getColumnModel().getColumn(1).setPreferredWidth(85);
            tabelaPesquisaAnimais.getColumnModel().getColumn(2).setPreferredWidth(85);
            tabelaPesquisaAnimais.getColumnModel().getColumn(3).setPreferredWidth(85);
            tabelaPesquisaAnimais.getColumnModel().getColumn(4).setPreferredWidth(85);
            tabelaPesquisaAnimais.getColumnModel().getColumn(5).setPreferredWidth(85);
        }

        jButton1.setText(">>>>>>>>>>>>>>>>>>>>>>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("remover");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Limpar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Número de Animais:"));

        jLabel11.setText("Femêa:");

        jLabel17.setText("Machos:");

        jLabel18.setText("Total:");

        jtTotalAnimais.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtTotalAnimais.setEnabled(false);
        jtTotalAnimais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtTotalAnimaisActionPerformed(evt);
            }
        });
        jtTotalAnimais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtTotalAnimaisKeyReleased(evt);
            }
        });

        jtAnimaisFemeas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtAnimaisFemeas.setEnabled(false);
        jtAnimaisFemeas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtAnimaisFemeasActionPerformed(evt);
            }
        });

        jtAnimaisMachos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtAnimaisMachos.setEnabled(false);
        jtAnimaisMachos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtAnimaisMachosActionPerformed(evt);
            }
        });
        jtAnimaisMachos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtAnimaisMachosKeyReleased(evt);
            }
        });

        jLabel19.setText("Mortos:");

        jtAnimaisMortos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtAnimaisMortos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtAnimaisMortosActionPerformed(evt);
            }
        });
        jtAnimaisMortos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtAnimaisMortosKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtTotalAnimais, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtAnimaisFemeas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtAnimaisMachos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtAnimaisMortos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jtTotalAnimais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jtAnimaisMachos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtAnimaisFemeas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jtAnimaisMortos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 16, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(79, 79, 79)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pesquisa_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisa_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisa_IdActionPerformed

    private void pesquisa_loteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisa_loteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisa_loteActionPerformed

    private void pesquisa_IdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisa_IdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisa_IdadeActionPerformed

    private void compoTipoVendaPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_compoTipoVendaPopupMenuWillBecomeInvisible
        int index = compoTipoVenda.getSelectedIndex();
        /*
        1 == pesquisa por lote
        2 == pesquisa por pasto
        3 == pesquisa por animais
         */

        if (index == 1) {
            pesquisa_Id.setEnabled(false);
            pesquisa_SegundaId.setEnabled(false);
            pesquisa_Idade.setEnabled(false);
            pesquisa_comboPasto.setEnabled(false);
            pesquisa_ComboTipoAnimal.setEnabled(false);
            pesquisa_Sexo.setEnabled(false);
            pesquisa_lote.setEnabled(false);
            BotaoPesquisa_Pesquisa.setEnabled(false);

            comboPasto.setEnabled(false);

            comboLote.setEnabled(true);

            try {
                pesquisaLote();
            } catch (SQLException ex) {
                Logger.getLogger(VendasAnimais.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (index == 2) {
            pesquisa_Id.setEnabled(false);
            pesquisa_SegundaId.setEnabled(false);
            pesquisa_Idade.setEnabled(false);
            pesquisa_comboPasto.setEnabled(false);
            pesquisa_ComboTipoAnimal.setEnabled(false);
            pesquisa_Sexo.setEnabled(false);
            pesquisa_lote.setEnabled(false);
            BotaoPesquisa_Pesquisa.setEnabled(false);

            comboLote.setEnabled(false);

            comboPasto.setEnabled(true);

            try {
                pesquisaPasto();
            } catch (SQLException ex) {
                Logger.getLogger(VendasAnimais.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (index == 3) {
            comboPasto.setEnabled(false);

            comboLote.setEnabled(false);

            pesquisa_Id.setEnabled(true);
            pesquisa_SegundaId.setEnabled(true);
            pesquisa_Idade.setEnabled(true);
            pesquisa_comboPasto.setEnabled(true);
            pesquisa_ComboTipoAnimal.setEnabled(true);
            pesquisa_Sexo.setEnabled(true);
            pesquisa_lote.setEnabled(true);
            BotaoPesquisa_Pesquisa.setEnabled(true);
            tabelaPesquisaAnimais.setEnabled(true);
            try {
                pesquisaTipoAnimal();
                pesquisaPasto();
            } catch (SQLException ex) {
                Logger.getLogger(VendasAnimais.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_compoTipoVendaPopupMenuWillBecomeInvisible

    private void comboLotePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboLotePopupMenuWillBecomeInvisible
        String lote = (String) comboLote.getSelectedItem();

        if (!lote.equals("Selecionar")) {
            limparTabela(tabelaVendaAnimais);

            try {
                carregarLote(lote);
            } catch (SQLException ex) {
                Logger.getLogger(VendasAnimais.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_comboLotePopupMenuWillBecomeInvisible

    private void comboPastoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboPastoPopupMenuWillBecomeInvisible
        String pasto = (String) comboPasto.getSelectedItem();

        if (!pasto.equals("Selecionar")) {
            limparTabela(tabelaVendaAnimais);
            try {
                carregarPasto(pasto);
            } catch (SQLException ex) {
                Logger.getLogger(VendasAnimais.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_comboPastoPopupMenuWillBecomeInvisible

    private void pesquisa_comboPastoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_pesquisa_comboPastoPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisa_comboPastoPopupMenuWillBecomeInvisible

    private void BotaoPesquisa_PesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoPesquisa_PesquisaActionPerformed
        Integer id = null, idade = null, lote = null;

        if (!pesquisa_Id.getText().equals("")) {
            id = Integer.parseInt(pesquisa_Id.getText());
        }
        if (!pesquisa_Idade.getText().equals("")) {
            idade = Integer.parseInt(pesquisa_Idade.getText());
        }
        if (!pesquisa_lote.getText().equals("")) {
            lote = Integer.parseInt(pesquisa_lote.getText());
        }

        String pasto = (String) pesquisa_comboPasto.getSelectedItem();
        String sexo = pesquisa_Sexo.getText();
        String tipoAnimal = (String) pesquisa_ComboTipoAnimal.getSelectedItem();
        String segundaId = pesquisa_SegundaId.getText();

        limparTabela(tabelaPesquisaAnimais);

        try {
            pesquisaAnimais(id, idade, lote, pasto, sexo, tipoAnimal, segundaId);
        } catch (SQLException ex) {
            Logger.getLogger(VendasAnimais.class.getName()).log(Level.SEVERE, null, ex);
        }
        somaTotais();
    }//GEN-LAST:event_BotaoPesquisa_PesquisaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        addTabelaVendaAnimias();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        removeTabelaVendaAnimias();
        somaTotais();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        limparTabela(tabelaVendaAnimais);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTReaisTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTReaisTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTReaisTotalActionPerformed

    private void jtTotalAnimaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtTotalAnimaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtTotalAnimaisActionPerformed

    private void jtTotalAnimaisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtTotalAnimaisKeyReleased

    }//GEN-LAST:event_jtTotalAnimaisKeyReleased

    private void jtAnimaisFemeasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtAnimaisFemeasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtAnimaisFemeasActionPerformed

    private void jtAnimaisMachosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtAnimaisMachosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtAnimaisMachosActionPerformed

    private void jtAnimaisMachosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtAnimaisMachosKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtAnimaisMachosKeyReleased

    private void jtAnimaisMortosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtAnimaisMortosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtAnimaisMortosActionPerformed

    private void jtAnimaisMortosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtAnimaisMortosKeyReleased
        somaTotais();
    }//GEN-LAST:event_jtAnimaisMortosKeyReleased

    private void jTTotalArrobaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTTotalArrobaKeyReleased
        somaTotais();
    }//GEN-LAST:event_jTTotalArrobaKeyReleased

    private void jTReaisArrobaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTReaisArrobaKeyReleased
        somaTotais();
    }//GEN-LAST:event_jTReaisArrobaKeyReleased

    private void jTReaisManejoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTReaisManejoKeyReleased
        somaTotais();
    }//GEN-LAST:event_jTReaisManejoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendasAnimais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendasAnimais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendasAnimais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendasAnimais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendasAnimais().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoPesquisa_Pesquisa;
    private javax.swing.JComboBox<String> comboLote;
    private javax.swing.JComboBox<String> comboPasto;
    private javax.swing.JComboBox<String> compoTipoVenda;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTMediaArroba;
    private javax.swing.JTextField jTReaisArroba;
    private javax.swing.JTextField jTReaisManejo;
    private javax.swing.JTextField jTReaisTotal;
    private javax.swing.JTextField jTTotalArroba;
    private javax.swing.JTextField jtAnimaisFemeas;
    private javax.swing.JTextField jtAnimaisMachos;
    private javax.swing.JTextField jtAnimaisMortos;
    private javax.swing.JTextField jtTotalAnimais;
    private javax.swing.JComboBox<String> pesquisa_ComboTipoAnimal;
    private javax.swing.JTextField pesquisa_Id;
    private javax.swing.JTextField pesquisa_Idade;
    private javax.swing.JTextField pesquisa_SegundaId;
    private javax.swing.JTextField pesquisa_Sexo;
    private javax.swing.JComboBox<String> pesquisa_comboPasto;
    private javax.swing.JTextField pesquisa_lote;
    private javax.swing.JTable tabelaPesquisaAnimais;
    private javax.swing.JTable tabelaVendaAnimais;
    // End of variables declaration//GEN-END:variables

    private void pesquisaTipoAnimal() throws SQLException {

        conexao conexao = new conexao();
        conexao.getConexao();
        String selectSQL = "SELECT * FROM tipoAnimal A ";

        Statement pstmtCon;
        pstmtCon = conexao.getConexao().createStatement();

        ResultSet rs = pstmtCon.executeQuery(selectSQL);

        pesquisa_ComboTipoAnimal.removeAllItems();
        pesquisa_ComboTipoAnimal.addItem("Selecionar");

        while (rs.next()) {

            pesquisa_ComboTipoAnimal.addItem(rs.getString("descricao"));

        }

        rs.close();
        pstmtCon.close();
    }

    private void pesquisaLote() throws SQLException {
        conexao conexao = new conexao();
        conexao.getConexao();
        String selectSQL = "SELECT * FROM lotes A where a.statusLote like 'COMPRA' and a.cod_fazenda = " + cod_fazenda;

        Statement pstmtCon;
        pstmtCon = conexao.getConexao().createStatement();

        ResultSet rs = pstmtCon.executeQuery(selectSQL);

        comboLote.removeAllItems();
        comboLote.addItem("Selecionar");

        while (rs.next()) {

            comboLote.addItem(rs.getString("numeroLote"));

        }

        rs.close();
        pstmtCon.close();

    }

    private void pesquisaPasto() throws SQLException {
        conexao conexao = new conexao();
        conexao.getConexao();
        String selectSQL = "SELECT * FROM pastos A where a.cod_fazenda = " + cod_fazenda;

        Statement pstmtCon;
        pstmtCon = conexao.getConexao().createStatement();

        ResultSet rs = pstmtCon.executeQuery(selectSQL);

        comboPasto.removeAllItems();
        comboPasto.addItem("Selecionar");

        while (rs.next()) {

            comboPasto.addItem(rs.getString("pasto"));
            pesquisa_comboPasto.addItem(rs.getString("pasto"));
        }

        rs.close();
        pstmtCon.close();

    }

    private void carregarLote(String lote) throws SQLException {

        conexao conexao = new conexao();
        conexao.getConexao();
        String selectSQL = "SELECT * FROM animais A where A.loteCompra = " + lote + " and a.cod_fazenda = " + cod_fazenda;

        Statement pstmtCon;
        pstmtCon = conexao.getConexao().createStatement();

        ResultSet rs = pstmtCon.executeQuery(selectSQL);

        while (rs.next()) {

            DefaultTableModel tabela = (DefaultTableModel) tabelaVendaAnimais.getModel();
            tabela.addRow(new String[]{rs.getString("identificacao"), rs.getString("loteCompra"),
                rs.getString("pasto"), rs.getString("idade"),
                rs.getString("Sexo"), rs.getString("tipoAnimal")});

        }

        tabelaVendaAnimais.setAutoResizeMode(tabelaVendaAnimais.AUTO_RESIZE_OFF); //adiciona barra de rolagem horizontal na tabela
        tabelaVendaAnimais.setDefaultRenderer(Object.class, new CellRenderer()); //chama class CellRenderer para centralizar conteudo da tabela

        rs.close();
        pstmtCon.close();

        somaTotais();
    }

    private void addTabelaVendaAnimias() {

        int linha = tabelaPesquisaAnimais.getSelectedRow();

        String id = (String) tabelaPesquisaAnimais.getValueAt(linha, 0);
        String loteCompra = (String) tabelaPesquisaAnimais.getValueAt(linha, 1);
        String pasto = (String) tabelaPesquisaAnimais.getValueAt(linha, 2);
        String idade = (String) tabelaPesquisaAnimais.getValueAt(linha, 3);
        String sexo = (String) tabelaPesquisaAnimais.getValueAt(linha, 4);
        String tipoAnimal = (String) tabelaPesquisaAnimais.getValueAt(linha, 5);

        DefaultTableModel tabela = (DefaultTableModel) tabelaVendaAnimais.getModel();
        tabela.addRow(new String[]{id, loteCompra, pasto, idade, sexo, tipoAnimal});

        somaTotais();
    }

    private void somaTotais() {
        int totalAnimais = tabelaVendaAnimais.getRowCount();
        int mortos = 0;
        if (!jtAnimaisMortos.getText().equals("")) {
            mortos = Integer.parseInt(jtAnimaisMortos.getText());
        }

        int macho = 0, femea = 0, linha = 0;
        if (totalAnimais > 0) {
            while (linha < totalAnimais) {
                String sexo = (String) tabelaVendaAnimais.getValueAt(linha, 4);
                if (sexo.equals("M")) {
                    macho++;
                }
                if (sexo.equals("F")) {
                    femea++;
                }
                linha++;
            }
            jtAnimaisFemeas.setText(String.valueOf(femea));
            jtAnimaisMachos.setText(String.valueOf(macho));

            if (!jTTotalArroba.getText().equals("")) {
                int totalArroba = Integer.parseInt(jTTotalArroba.getText());
                double mediaArroba = totalArroba / totalAnimais;
                jTMediaArroba.setText(String.valueOf(mediaArroba));
            }

        }else{
            jtAnimaisFemeas.setText("0");
            jtAnimaisMachos.setText("0");
            jtTotalAnimais.setText("0");
        }

        totalAnimais = totalAnimais + mortos;
        jtTotalAnimais.setText(String.valueOf(totalAnimais));

        if (!jTReaisArroba.getText().equals("") && !jTTotalArroba.getText().equals("")) {
            int reaisArroba = Integer.parseInt(jTReaisArroba.getText());
            int totalArroba = Integer.parseInt(jTTotalArroba.getText());

            int manejo = 0;
            if (!jTReaisManejo.getText().equals("")) {
                manejo = Integer.parseInt(jTReaisManejo.getText());
            }

            double totalReias = manejo + (reaisArroba * totalArroba);
            jTReaisTotal.setText(String.valueOf(totalReias));
        }

    }

    private void removeTabelaVendaAnimias() {
        int linha = tabelaVendaAnimais.getSelectedRow();

        DefaultTableModel tabela = (DefaultTableModel) tabelaVendaAnimais.getModel();
        if (linha >= 0) {
            tabela.removeRow(linha);
        }
    }

    private void carregarPasto(String pasto) throws SQLException {

        conexao conexao = new conexao();
        conexao.getConexao();
        String selectSQL = "SELECT * FROM animais A where A.pasto like '" + pasto + "'";

        Statement pstmtCon;
        pstmtCon = conexao.getConexao().createStatement();

        ResultSet rs = pstmtCon.executeQuery(selectSQL);

        while (rs.next()) {

            DefaultTableModel tabela = (DefaultTableModel) tabelaVendaAnimais.getModel();
            tabela.addRow(new String[]{rs.getString("identificacao"), rs.getString("loteCompra"),
                rs.getString("pasto"), rs.getString("idade"),
                rs.getString("Sexo"), rs.getString("tipoAnimal")});

        }

        tabelaVendaAnimais.setAutoResizeMode(tabelaVendaAnimais.AUTO_RESIZE_OFF); //adiciona barra de rolagem horizontal na tabela
        tabelaVendaAnimais.setDefaultRenderer(Object.class, new CellRenderer()); //chama class CellRenderer para centralizar conteudo da tabela

        rs.close();
        pstmtCon.close();

        somaTotais();
    }

    private void pesquisaAnimais(Integer id, Integer idade, Integer lote, String pasto,
            String sexo, String tipoAnimal, String segundaId) throws SQLException {

        conexao conexao = new conexao();
        conexao.getConexao();
        String selectSQL = "SELECT * FROM animais A where A.cod_status <> 1 and a.cod_status <> 3 and a.cod_fazenda = " + cod_fazenda;

        if (id != null) {
            selectSQL = selectSQL + " and A.identificacao = " + id;
        }
        if (idade != null) {
            selectSQL = selectSQL + " and A.idade = " + idade;
        }
        if (lote != null) {
            selectSQL = selectSQL + " and A.loteCompra = " + lote;
        }
        if (!pasto.equals("Selecionar")) {
            selectSQL = selectSQL + " and A.pasto like '" + pasto + " ' ";
        }
        if (!sexo.equals("")) {
            selectSQL = selectSQL + " and A.sexo = '" + sexo + " ' ";
        }
        if (!tipoAnimal.equals("Selecionar")) {
            selectSQL = selectSQL + " and A.tipoAnimal like '" + tipoAnimal + " ' ";
        }
        if (!segundaId.equals("")) {
            selectSQL = selectSQL + " and A.identificacao2 like '" + segundaId + " ' ";
        }

        Statement pstmtCon;
        pstmtCon = conexao.getConexao().createStatement();

        ResultSet rs = pstmtCon.executeQuery(selectSQL);

        while (rs.next()) {

            DefaultTableModel tabela = (DefaultTableModel) tabelaPesquisaAnimais.getModel();
            tabela.addRow(new String[]{rs.getString("identificacao"), rs.getString("loteCompra"),
                rs.getString("pasto"), rs.getString("idade"),
                rs.getString("Sexo"), rs.getString("tipoAnimal")});

        }

        tabelaPesquisaAnimais.setAutoResizeMode(tabelaPesquisaAnimais.AUTO_RESIZE_OFF); //adiciona barra de rolagem horizontal na tabela
        tabelaPesquisaAnimais.setDefaultRenderer(Object.class, new CellRenderer()); //chama class CellRenderer para centralizar conteudo da tabela

        rs.close();
        pstmtCon.close();
    }

    private void limparTabela(JTable nomeTabela) {
        DefaultTableModel tabela = (DefaultTableModel) nomeTabela.getModel();
        int numeroLinhas = tabela.getRowCount();
        int index = 1;

        while (index <= numeroLinhas) {
            tabela.removeRow(0);
            index++;
        }

        somaTotais();
    }

    // classe e metodo abaixo usados para centralizar conteudo da tabela
    public class CellRenderer extends DefaultTableCellRenderer {

        public CellRenderer() {
            super();
        }

        public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
            this.setHorizontalAlignment(CENTER);
            return super.getTableCellRendererComponent(table, value, isSelected,
                    hasFocus, row, column);
        }
    }
}
