/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceCadastro;

import ClassesDados.pastos;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.IncluirEditarDAO;
import persistencia.conexao;

/**
 *
 * @author Igor
 */
public class CadastroPastos extends javax.swing.JFrame {

    IncluirEditarDAO cadastroP;
    pastos pastos = new pastos();
    String selecao;
    int codSelecao;

    private int cod_fazenda;

    public CadastroPastos(int codFazenda) {
        cod_fazenda = codFazenda;

        initComponents();
        setExtendedState(MAXIMIZED_BOTH);

        Date dataSistema = new Date();
        campoDtCadastro.setDate(dataSistema);
        campoDtUltimaAteracao.setDate(dataSistema);

        try {
            consultaPastos();
        } catch (SQLException ex) {
            Logger.getLogger(CadastroPastos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public CadastroPastos() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaResultado = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        campoB = new javax.swing.JTextField();
        campoC = new javax.swing.JTextField();
        campoD = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        campoDiagonal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        campoPerimetro = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        campoArea = new javax.swing.JTextField();
        botaoCalcular = new javax.swing.JButton();
        campoA = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        botaoApagar = new javax.swing.JButton();
        campoDtCadastro = new com.toedter.calendar.JDateChooser();
        campoDtUltimaAteracao = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        botaoCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        botaoNovo = new javax.swing.JButton();
        campoCod = new javax.swing.JTextField();
        campoDescricao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboStatus = new javax.swing.JComboBox<>();
        botaoSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Pastos");

        tabelaResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código:", "Descrição:", "Status:", "Lado A:", "Lado B:", "Lado C:", "Lado D:", "Diagonal:", "Perimetro:", "Área:", "Cadastro:", "Alteração:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaResultado);
        if (tabelaResultado.getColumnModel().getColumnCount() > 0) {
            tabelaResultado.getColumnModel().getColumn(0).setMinWidth(50);
            tabelaResultado.getColumnModel().getColumn(0).setPreferredWidth(50);
            tabelaResultado.getColumnModel().getColumn(0).setMaxWidth(50);
            tabelaResultado.getColumnModel().getColumn(3).setMinWidth(50);
            tabelaResultado.getColumnModel().getColumn(3).setPreferredWidth(50);
            tabelaResultado.getColumnModel().getColumn(3).setMaxWidth(50);
            tabelaResultado.getColumnModel().getColumn(4).setMinWidth(50);
            tabelaResultado.getColumnModel().getColumn(4).setPreferredWidth(50);
            tabelaResultado.getColumnModel().getColumn(4).setMaxWidth(50);
            tabelaResultado.getColumnModel().getColumn(5).setMinWidth(50);
            tabelaResultado.getColumnModel().getColumn(5).setPreferredWidth(50);
            tabelaResultado.getColumnModel().getColumn(5).setMaxWidth(50);
            tabelaResultado.getColumnModel().getColumn(6).setMinWidth(50);
            tabelaResultado.getColumnModel().getColumn(6).setPreferredWidth(50);
            tabelaResultado.getColumnModel().getColumn(6).setMaxWidth(50);
        }

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dimenssões para calculo da área:"));

        jLabel7.setText("Lado A:");

        jLabel8.setText("Lado B:");

        campoB.setEnabled(false);

        campoC.setEnabled(false);

        campoD.setEnabled(false);

        jLabel9.setText("Lado C:");

        jLabel10.setText("Lado D:");

        campoDiagonal.setEnabled(false);

        jLabel11.setText("Diagonal:");

        campoPerimetro.setEnabled(false);

        jLabel12.setText("Perimetro:");

        jLabel13.setText("Área:");

        campoArea.setEnabled(false);

        botaoCalcular.setText("Calcular");
        botaoCalcular.setEnabled(false);
        botaoCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCalcularActionPerformed(evt);
            }
        });

        campoA.setEnabled(false);

        jLabel14.setText("Observe a imagem abaixo para inserir os valores:");

        jLabel15.setText("Ou você pode inserir a Área direto:");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CadastroPastos_lados.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(campoA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(campoDiagonal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoD, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botaoCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoArea, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoDiagonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel8)
                                .addGap(2, 2, 2)
                                .addComponent(campoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel9)
                                .addGap(6, 6, 6)
                                .addComponent(campoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel10)
                                .addGap(9, 9, 9)
                                .addComponent(campoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel12)
                                .addGap(2, 2, 2)
                                .addComponent(campoPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel13)
                                .addGap(6, 6, 6)
                                .addComponent(campoArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(botaoCalcular))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)))
                .addContainerGap())
        );

        botaoApagar.setText("Apagar");

        campoDtCadastro.setEnabled(false);

        campoDtUltimaAteracao.setEnabled(false);

        jLabel4.setText("Ultima da de alteração:");

        botaoCancelar.setText("Cancelar");
        botaoCancelar.setEnabled(false);
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        jLabel5.setText("Data de cadastro:");

        botaoNovo.setText("Novo");
        botaoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNovoActionPerformed(evt);
            }
        });

        campoCod.setEnabled(false);

        campoDescricao.setEnabled(false);
        campoDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDescricaoActionPerformed(evt);
            }
        });
        campoDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoDescricaoKeyReleased(evt);
            }
        });

        jLabel1.setText("  Código:");

        jLabel2.setText("Descrição:");

        jLabel3.setText("Status:");

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar" }));
        comboStatus.setEnabled(false);

        botaoSalvar.setText("Salvar");
        botaoSalvar.setEnabled(false);
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(campoCod, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botaoSalvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(botaoApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoDtCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoDtUltimaAteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(botaoNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(3, 3, 3)
                                            .addComponent(jLabel1))
                                        .addComponent(campoCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(113, 113, 113)
                                    .addComponent(jLabel2)
                                    .addGap(17, 17, 17)
                                    .addComponent(campoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(48, 48, 48)
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(113, 113, 113)
                                    .addComponent(botaoSalvar)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(botaoApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(78, 78, 78)
                                    .addComponent(jLabel5)
                                    .addGap(17, 17, 17)
                                    .addComponent(campoDtCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(48, 48, 48)
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(campoDtUltimaAteracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(377, 377, 377)
                                    .addComponent(botaoCancelar))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1332, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDescricaoActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_campoDescricaoActionPerformed

    private void campoDescricaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoDescricaoKeyReleased
        campoDescricao.setText(campoDescricao.getText().toUpperCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDescricaoKeyReleased

    private void botaoCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCalcularActionPerformed

        int A, B, C, D, diagonal;
        A = Integer.parseInt(campoA.getText());
        B = Integer.parseInt(campoB.getText());
        C = Integer.parseInt(campoC.getText());
        D = Integer.parseInt(campoD.getText());
        diagonal = Integer.parseInt(campoDiagonal.getText());

        double perimetro1, perimetro2;

        perimetro1 = A + B + diagonal;
        perimetro2 = C + D + diagonal;

        //calculo perimetro1
        perimetro1 = perimetro1 / 2;

        double rais1 = perimetro1 * (perimetro1 - A) * (perimetro1 - B) * (perimetro1 - diagonal);
        rais1 = Math.sqrt(rais1);

        //calculo perimetro2
        perimetro2 = perimetro2 / 2;

        double rais2 = perimetro2 * (perimetro2 - C) * (perimetro2 - D) * (perimetro2 - diagonal);
        rais2 = Math.sqrt(rais2);

        //totais
        int area = (int) (rais1 + rais2);

        String areaS = String.valueOf(area);
        String perimetroTotal = String.valueOf(A + B + C + D);
        campoArea.setText(areaS);
        campoPerimetro.setText(perimetroTotal);
    }//GEN-LAST:event_botaoCalcularActionPerformed

    private void botaoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovoActionPerformed

        campoDescricao.setEnabled(true);
        campoA.setEnabled(true);
        campoB.setEnabled(true);
        campoC.setEnabled(true);
        campoD.setEnabled(true);
        campoArea.setEnabled(true);
        campoDiagonal.setEnabled(true);
        campoPerimetro.setEnabled(true);
        comboStatus.setEnabled(true);

        botaoApagar.setEnabled(false);
        botaoSalvar.setEnabled(true);
        botaoNovo.setEnabled(false);
        botaoCancelar.setEnabled(true);
        botaoCalcular.setEnabled(true);

        campoDescricao.setText("");
        campoCod.setText("");
        campoA.setText("0");
        campoB.setText("0");
        campoC.setText("0");
        campoD.setText("0");
        campoArea.setText("0");
        campoDiagonal.setText("0");
        campoPerimetro.setText("0");

        try {
            consultaStatus();
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(CadastroPastos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoNovoActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed

        botaoSalvar.setEnabled(false);
        botaoApagar.setEnabled(true);
        botaoNovo.setEnabled(true);
        botaoCancelar.setEnabled(false);
        botaoCalcular.setEnabled(false);

        campoDescricao.setEnabled(false);
        campoA.setEnabled(false);
        campoB.setEnabled(false);
        campoC.setEnabled(false);
        campoD.setEnabled(false);
        campoDiagonal.setEnabled(false);
        campoArea.setEnabled(false);
        campoPerimetro.setEnabled(false);

        comboStatus.setEnabled(false);
        comboStatus.setSelectedIndex(0);

        campoDescricao.setText("");
        campoA.setText("");
        campoB.setText("");
        campoC.setText("");
        campoD.setText("");
        campoDiagonal.setText("");
        campoArea.setText("");
        campoPerimetro.setText("");

        comboStatus.removeAllItems();
        comboStatus.addItem("Selecionar");
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed

        int cod;
        int acao = 1;

        preencher();

        try {

        } catch (Exception error) {
            JOptionPane.showMessageDialog(this, "Erro" + error.getMessage());
        }

        try {
            cadastroP = new IncluirEditarDAO();
            if (acao == 1) {
                cod = cadastroP.IncluirCadastroPastos(pastos);
                campoCod.setText(String.valueOf(cod));
                JOptionPane.showMessageDialog(this, "Salvo com sucesso!");
                //salvar();
            }
        } catch (SQLException | HeadlessException error) {
            JOptionPane.showMessageDialog(this, "Operação não realizada" + error.getMessage());
        }
        botaoSalvar.setEnabled(false);
        campoDescricao.setEnabled(false);
        botaoApagar.setEnabled(true);
        botaoNovo.setEnabled(true);
        botaoCancelar.setEnabled(false);

        while (tabelaResultado.getModel().getRowCount() > 0) {
            ((DefaultTableModel) tabelaResultado.getModel()).removeRow(0);
        }

        try {
            consultaPastos();
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(CadastroStatus.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroPastos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoApagar;
    private javax.swing.JButton botaoCalcular;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoNovo;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JTextField campoA;
    private javax.swing.JTextField campoArea;
    private javax.swing.JTextField campoB;
    private javax.swing.JTextField campoC;
    private javax.swing.JTextField campoCod;
    private javax.swing.JTextField campoD;
    private javax.swing.JTextField campoDescricao;
    private javax.swing.JTextField campoDiagonal;
    private com.toedter.calendar.JDateChooser campoDtCadastro;
    private com.toedter.calendar.JDateChooser campoDtUltimaAteracao;
    private javax.swing.JTextField campoPerimetro;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaResultado;
    // End of variables declaration//GEN-END:variables

    public void consultaStatus() throws SQLException {

        conexao conexao = new conexao();
        conexao.getConexao();
        String selectSQL = "SELECT * FROM statusPastos A ";

        Statement pstmtCon;
        pstmtCon = conexao.getConexao().createStatement();

        ResultSet rs = pstmtCon.executeQuery(selectSQL);

        while (rs.next()) {

            DefaultTableModel tabela = (DefaultTableModel) tabelaResultado.getModel();
            comboStatus.addItem(rs.getString("status"));
        }

        rs.close();
        pstmtCon.close();

    }

    public void preencher() {

        pastos.setPasto(campoDescricao.getText());
        pastos.setStatus((String) comboStatus.getSelectedItem());

        int temp;
        temp = Integer.parseInt(campoA.getText());
        pastos.setLadoA(temp);

        temp = Integer.parseInt(campoB.getText());
        pastos.setLadoB(temp);

        temp = Integer.parseInt(campoC.getText());
        pastos.setLadoC(temp);

        temp = Integer.parseInt(campoD.getText());
        pastos.setLadoD(temp);

        temp = Integer.parseInt(campoDiagonal.getText());
        pastos.setDiagonal(temp);

        temp = Integer.parseInt(campoPerimetro.getText());
        pastos.setPerimetro(temp);

        temp = Integer.parseInt(campoArea.getText());
        pastos.setArea(temp);

        pastos.setDtCadastro(campoDtCadastro.getDate());
        pastos.setDtUltimaAteracao(campoDtUltimaAteracao.getDate());

        selecao = (String) comboStatus.getSelectedItem();

        try {
            codSelecao();
        } catch (SQLException ex) {
            Logger.getLogger(CadastroRacaAnimal.class.getName()).log(Level.SEVERE, null, ex);
        }

        pastos.setCod_status(codSelecao);
        pastos.setCod_fazenda(cod_fazenda);

    }

    public void consultaPastos() throws SQLException {

        conexao conexao = new conexao();
        conexao.getConexao();
        String selectSQL = "SELECT * FROM pastos A where a.cod_fazenda = " + cod_fazenda;

        Statement pstmtCon;
        pstmtCon = conexao.getConexao().createStatement();

        ResultSet rs = pstmtCon.executeQuery(selectSQL);

        while (rs.next()) {

            DefaultTableModel tabela = (DefaultTableModel) tabelaResultado.getModel();
            tabela.addRow(new String[]{rs.getString("cod_pasto"), rs.getString("pasto"), rs.getString("status"),
                rs.getString("ladoA"), rs.getString("ladoB"), rs.getString("ladoC"), rs.getString("ladoD"),
                rs.getString("diagonal"), rs.getString("perimetro"), rs.getString("area"), rs.getString("dtCadastro"), rs.getString("dtUltimaAteracao")});

        }

        rs.close();
        pstmtCon.close();

    }

    public void codSelecao() throws SQLException {

        conexao conexao = new conexao();
        conexao.getConexao();
        String selectSQL = "SELECT * FROM statusPastos A WHERE A.status LIKE '" + selecao + "'";

        Statement pstmtCon;
        pstmtCon = conexao.getConexao().createStatement();

        ResultSet rs = pstmtCon.executeQuery(selectSQL);

        while (rs.next()) {

            codSelecao = Integer.parseInt(rs.getString("cod_status"));
        }

        rs.close();
        pstmtCon.close();

    }
}
