package InterfaceCadastro;

import ClassesDados.fazendaConfinamento;
import ClassesDados.fazenda;
import java.awt.HeadlessException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import persistencia.IncluirEditarDAO;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import persistencia.conexao;

public class Fazenda extends javax.swing.JFrame {

    IncluirEditarDAO faz;
    fazenda fazenda = new fazenda();
    fazendaConfinamento fazendaConfinamento = new fazendaConfinamento();

    private int cod_fazenda;
    
    public Fazenda(int codFazenda) {
        cod_fazenda = codFazenda;
        
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);

        try {
            consultaFazenda();
            consultaFazendaConfinamento();
        } catch (SQLException ex) {
            Logger.getLogger(Fazenda.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private Fazenda() {
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abas = new javax.swing.JTabbedPane();
        abaFazenda = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        opcaoCriacaoDeAves = new javax.swing.JCheckBox();
        opcaoLeite = new javax.swing.JCheckBox();
        opcaoConfinamento = new javax.swing.JCheckBox();
        opcaoPlantacao = new javax.swing.JCheckBox();
        botaoSalvarFazenda = new javax.swing.JButton();
        abaConfinamento = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        alimentacao1 = new javax.swing.JTextField();
        alimentacao2 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        alimentacao4 = new javax.swing.JTextField();
        alimentacao3 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        KgDiaGarrotes = new javax.swing.JTextField();
        KgDiaBezerros = new javax.swing.JTextField();
        KgDiaBois = new javax.swing.JTextField();
        KgDiaBoisVelhos = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        periodo4B = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        periodo2A = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        periodo3A = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        periodo4A = new javax.swing.JTextField();
        periodo1A = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        periodo1B = new javax.swing.JTextField();
        periodo2B = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        periodo3B = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        bezerrosA = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        bezerrosB = new javax.swing.JTextField();
        garrotesB = new javax.swing.JTextField();
        boisB = new javax.swing.JTextField();
        boisVelhosB = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        boisVelhosA = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        garrotesA = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        boisA = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        m2BoisVelhos = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        m2Bezerros = new javax.swing.JTextField();
        m2Garrotes = new javax.swing.JTextField();
        m2Bois = new javax.swing.JTextField();
        botaoSalvarConfinamento = new javax.swing.JButton();
        abaLeite = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fazenda");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipos de Atividades:"));

        opcaoCriacaoDeAves.setText("Criação de Aves");

        opcaoLeite.setText("Leite");
        opcaoLeite.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                opcaoLeiteKeyReleased(evt);
            }
        });

        opcaoConfinamento.setText("Confinamento de Bovinos");
        opcaoConfinamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opcaoConfinamentoMouseClicked(evt);
            }
        });
        opcaoConfinamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcaoConfinamentoActionPerformed(evt);
            }
        });

        opcaoPlantacao.setText("Plantação");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opcaoCriacaoDeAves)
                    .addComponent(opcaoConfinamento)
                    .addComponent(opcaoLeite)
                    .addComponent(opcaoPlantacao))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(opcaoConfinamento)
                .addGap(18, 18, 18)
                .addComponent(opcaoLeite)
                .addGap(18, 18, 18)
                .addComponent(opcaoCriacaoDeAves)
                .addGap(18, 18, 18)
                .addComponent(opcaoPlantacao)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        botaoSalvarFazenda.setText("Salvar");
        botaoSalvarFazenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarFazendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoSalvarFazenda, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(955, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(botaoSalvarFazenda)
                .addContainerGap(283, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout abaFazendaLayout = new javax.swing.GroupLayout(abaFazenda);
        abaFazenda.setLayout(abaFazendaLayout);
        abaFazendaLayout.setHorizontalGroup(
            abaFazendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        abaFazendaLayout.setVerticalGroup(
            abaFazendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        abas.addTab("Fazenda", abaFazenda);

        abaConfinamento.setEnabled(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Alimentação em kg diaria:"));

        jLabel26.setText("Bezerros:");

        alimentacao1.setText("12");
        alimentacao1.setEnabled(false);

        alimentacao2.setText("13");
        alimentacao2.setEnabled(false);

        jLabel27.setText("Garrotes:");

        jLabel28.setText("Bois:");

        jLabel29.setText("Bois Velhos:");

        alimentacao4.setText("14");
        alimentacao4.setEnabled(false);

        alimentacao3.setText("14");
        alimentacao3.setEnabled(false);
        alimentacao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alimentacao3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(alimentacao1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(alimentacao2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(41, 41, 41)
                            .addComponent(alimentacao3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(alimentacao4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alimentacao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel26)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alimentacao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel27)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(alimentacao3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel28)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel29))
                    .addComponent(alimentacao4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Gando de kg diario:"));

        jLabel21.setText("Bois Velhos:");

        jLabel22.setText("Bois:");

        jLabel23.setText("Garrotes:");

        jLabel24.setText("Bezerros:");

        KgDiaGarrotes.setText("1.4");
        KgDiaGarrotes.setEnabled(false);

        KgDiaBezerros.setText("1.1");
        KgDiaBezerros.setEnabled(false);

        KgDiaBois.setText("1.3");
        KgDiaBois.setEnabled(false);
        KgDiaBois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KgDiaBoisActionPerformed(evt);
            }
        });

        KgDiaBoisVelhos.setText("1.2");
        KgDiaBoisVelhos.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(KgDiaBoisVelhos))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(KgDiaBois))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(KgDiaGarrotes))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(KgDiaBezerros, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KgDiaBezerros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel24)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KgDiaGarrotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel23)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(KgDiaBois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel22)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel21))
                    .addComponent(KgDiaBoisVelhos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Período de confinamneto em dias:"));

        periodo4B.setText("60");
        periodo4B.setEnabled(false);
        periodo4B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodo4BActionPerformed(evt);
            }
        });

        jLabel12.setText("Período 1:");

        jLabel13.setText("Período 2:");

        periodo2A.setText("100");
        periodo2A.setEnabled(false);

        jLabel14.setText("Período 3:");

        periodo3A.setText("60");
        periodo3A.setEnabled(false);
        periodo3A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodo3AActionPerformed(evt);
            }
        });

        jLabel15.setText("Período 4:");

        periodo4A.setText("30");
        periodo4A.setEnabled(false);
        periodo4A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodo4AActionPerformed(evt);
            }
        });

        periodo1A.setText("130");
        periodo1A.setEnabled(false);

        jLabel16.setText("até");

        periodo1B.setText("160");
        periodo1B.setEnabled(false);
        periodo1B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodo1BActionPerformed(evt);
            }
        });

        periodo2B.setText("120");
        periodo2B.setEnabled(false);

        jLabel17.setText("até");

        jLabel18.setText("até");

        periodo3B.setText("90");
        periodo3B.setEnabled(false);
        periodo3B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodo3BActionPerformed(evt);
            }
        });

        jLabel19.setText("até");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(6, 6, 6)
                        .addComponent(periodo1A, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel16)
                        .addGap(4, 4, 4)
                        .addComponent(periodo1B, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(4, 4, 4)
                                .addComponent(periodo4A, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel19)
                                .addGap(4, 4, 4)
                                .addComponent(periodo4B, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(4, 4, 4)
                                .addComponent(periodo3A, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel18)
                                .addGap(4, 4, 4)
                                .addComponent(periodo3B, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(4, 4, 4)
                                .addComponent(periodo2A, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel17)
                                .addGap(4, 4, 4)
                                .addComponent(periodo2B, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(periodo1A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(periodo1B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel16))))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(periodo2A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(periodo2B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel17))))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(periodo3A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(periodo3B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel18))))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(periodo4A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(periodo4B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel19))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Clasificaçãode idade em messes:"));

        jLabel3.setText("Bezerros:");

        bezerrosA.setText("0");
        bezerrosA.setEnabled(false);

        jLabel7.setText("até");

        bezerrosB.setText("14");
        bezerrosB.setEnabled(false);
        bezerrosB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bezerrosBActionPerformed(evt);
            }
        });

        garrotesB.setText("20");
        garrotesB.setEnabled(false);
        garrotesB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                garrotesBActionPerformed(evt);
            }
        });

        boisB.setText("31");
        boisB.setEnabled(false);
        boisB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boisBActionPerformed(evt);
            }
        });

        boisVelhosB.setText("50");
        boisVelhosB.setEnabled(false);
        boisVelhosB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boisVelhosBActionPerformed(evt);
            }
        });

        jLabel10.setText("até");

        boisVelhosA.setText("32");
        boisVelhosA.setEnabled(false);

        jLabel6.setText("Bois Velhos:");

        jLabel5.setText("Bois:");

        jLabel4.setText("Garrotes:");

        garrotesA.setText("15");
        garrotesA.setEnabled(false);

        jLabel8.setText("até");

        jLabel9.setText("até");

        boisA.setText("21");
        boisA.setEnabled(false);
        boisA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boisAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(boisVelhosA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel10)
                        .addGap(4, 4, 4)
                        .addComponent(boisVelhosB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(boisA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel9)
                        .addGap(4, 4, 4)
                        .addComponent(boisB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(garrotesA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel8)
                        .addGap(4, 4, 4)
                        .addComponent(garrotesB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(bezerrosA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel7)
                        .addGap(4, 4, 4)
                        .addComponent(bezerrosB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(bezerrosA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bezerrosB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(garrotesA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(garrotesB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel8)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(boisA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel9))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(boisB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6))
                    .addComponent(boisVelhosA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel10))
                    .addComponent(boisVelhosB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Metro quadrado por cabeça:"));

        m2BoisVelhos.setText("10");
        m2BoisVelhos.setEnabled(false);

        jLabel34.setText("Bois Velhos:");

        jLabel33.setText("Bois:");

        jLabel32.setText("Garrotes:");

        jLabel31.setText("Bezerros:");

        m2Bezerros.setText("6");
        m2Bezerros.setEnabled(false);

        m2Garrotes.setText("8");
        m2Garrotes.setEnabled(false);

        m2Bois.setText("10");
        m2Bois.setEnabled(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(m2BoisVelhos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(m2Bezerros, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(m2Garrotes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(m2Bois, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel31))
                    .addComponent(m2Bezerros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel32))
                    .addComponent(m2Garrotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(m2Bois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(m2BoisVelhos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        botaoSalvarConfinamento.setText("Salvar");
        botaoSalvarConfinamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarConfinamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botaoSalvarConfinamento, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                .addComponent(botaoSalvarConfinamento)
                .addGap(135, 135, 135))
        );

        javax.swing.GroupLayout abaConfinamentoLayout = new javax.swing.GroupLayout(abaConfinamento);
        abaConfinamento.setLayout(abaConfinamentoLayout);
        abaConfinamentoLayout.setHorizontalGroup(
            abaConfinamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        abaConfinamentoLayout.setVerticalGroup(
            abaConfinamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        abas.addTab("Confinamento", abaConfinamento);

        abaLeite.setEnabled(false);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1220, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout abaLeiteLayout = new javax.swing.GroupLayout(abaLeite);
        abaLeite.setLayout(abaLeiteLayout);
        abaLeiteLayout.setHorizontalGroup(
            abaLeiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        abaLeiteLayout.setVerticalGroup(
            abaLeiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        abas.addTab("Leite", abaLeite);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abas)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boisAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boisAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boisAActionPerformed

    private void bezerrosBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bezerrosBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bezerrosBActionPerformed

    private void garrotesBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_garrotesBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_garrotesBActionPerformed

    private void boisBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boisBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boisBActionPerformed

    private void boisVelhosBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boisVelhosBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boisVelhosBActionPerformed

    private void periodo3AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periodo3AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_periodo3AActionPerformed

    private void periodo4AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periodo4AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_periodo4AActionPerformed

    private void periodo1BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periodo1BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_periodo1BActionPerformed

    private void periodo3BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periodo3BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_periodo3BActionPerformed

    private void periodo4BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periodo4BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_periodo4BActionPerformed

    private void KgDiaBoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KgDiaBoisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KgDiaBoisActionPerformed

    private void alimentacao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alimentacao3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alimentacao3ActionPerformed

    private void opcaoLeiteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_opcaoLeiteKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_opcaoLeiteKeyReleased

    private void opcaoConfinamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcaoConfinamentoActionPerformed

    }//GEN-LAST:event_opcaoConfinamentoActionPerformed

    private void opcaoConfinamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcaoConfinamentoMouseClicked

        if (opcaoConfinamento.isSelected()) {
            bezerrosA.setEnabled(true);
            bezerrosB.setEnabled(true);
            garrotesA.setEnabled(true);
            garrotesB.setEnabled(true);
            boisA.setEnabled(true);
            boisB.setEnabled(true);
            boisVelhosA.setEnabled(true);
            boisVelhosB.setEnabled(true);

            periodo1A.setEnabled(true);
            periodo1B.setEnabled(true);
            periodo2A.setEnabled(true);
            periodo2B.setEnabled(true);
            periodo3A.setEnabled(true);
            periodo3B.setEnabled(true);
            periodo4A.setEnabled(true);
            periodo4B.setEnabled(true);

            KgDiaBezerros.setEnabled(true);
            KgDiaGarrotes.setEnabled(true);
            KgDiaBois.setEnabled(true);
            KgDiaBoisVelhos.setEnabled(true);

            alimentacao1.setEnabled(true);
            alimentacao2.setEnabled(true);
            alimentacao3.setEnabled(true);
            alimentacao4.setEnabled(true);

            m2Bezerros.setEnabled(true);
            m2Garrotes.setEnabled(true);
            m2Bois.setEnabled(true);
            m2BoisVelhos.setEnabled(true);
        }

        if (!opcaoConfinamento.isSelected()) {
            bezerrosA.setEnabled(false);
            bezerrosB.setEnabled(false);
            garrotesA.setEnabled(false);
            garrotesB.setEnabled(false);
            boisA.setEnabled(false);
            boisB.setEnabled(false);
            boisVelhosA.setEnabled(false);
            boisVelhosB.setEnabled(false);

            periodo1A.setEnabled(false);
            periodo1B.setEnabled(false);
            periodo2A.setEnabled(false);
            periodo2B.setEnabled(false);
            periodo3A.setEnabled(false);
            periodo3B.setEnabled(false);
            periodo4A.setEnabled(false);
            periodo4B.setEnabled(false);

            KgDiaBezerros.setEnabled(false);
            KgDiaGarrotes.setEnabled(false);
            KgDiaBois.setEnabled(false);
            KgDiaBoisVelhos.setEnabled(false);

            alimentacao1.setEnabled(false);
            alimentacao2.setEnabled(false);
            alimentacao3.setEnabled(false);
            alimentacao4.setEnabled(false);

            m2Bezerros.setEnabled(false);
            m2Garrotes.setEnabled(false);
            m2Bois.setEnabled(false);
            m2BoisVelhos.setEnabled(false);
        }
    }//GEN-LAST:event_opcaoConfinamentoMouseClicked

    private void botaoSalvarFazendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarFazendaActionPerformed

        preencherFazenda();

        faz = new IncluirEditarDAO();

        try {
            faz.AlterarFazenda(fazenda);
            JOptionPane.showMessageDialog(this, "Salvo com sucesso!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Operação não realizada" + ex.getMessage());
        }


    }//GEN-LAST:event_botaoSalvarFazendaActionPerformed

    private void botaoSalvarConfinamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarConfinamentoActionPerformed
        preencherFazendaConfinamento();

        faz = new IncluirEditarDAO();

        try {
            faz.AlterarFazendaCofinamento(fazendaConfinamento);
            JOptionPane.showMessageDialog(this, "Salvo com sucesso!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Operação não realizada" + ex.getMessage());
        }


    }//GEN-LAST:event_botaoSalvarConfinamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fazenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fazenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fazenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fazenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fazenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField KgDiaBezerros;
    private javax.swing.JTextField KgDiaBois;
    private javax.swing.JTextField KgDiaBoisVelhos;
    private javax.swing.JTextField KgDiaGarrotes;
    private javax.swing.JPanel abaConfinamento;
    private javax.swing.JPanel abaFazenda;
    private javax.swing.JPanel abaLeite;
    private javax.swing.JTabbedPane abas;
    private javax.swing.JTextField alimentacao1;
    private javax.swing.JTextField alimentacao2;
    private javax.swing.JTextField alimentacao3;
    private javax.swing.JTextField alimentacao4;
    private javax.swing.JTextField bezerrosA;
    private javax.swing.JTextField bezerrosB;
    private javax.swing.JTextField boisA;
    private javax.swing.JTextField boisB;
    private javax.swing.JTextField boisVelhosA;
    private javax.swing.JTextField boisVelhosB;
    private javax.swing.JButton botaoSalvarConfinamento;
    private javax.swing.JButton botaoSalvarFazenda;
    private javax.swing.JTextField garrotesA;
    private javax.swing.JTextField garrotesB;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField m2Bezerros;
    private javax.swing.JTextField m2Bois;
    private javax.swing.JTextField m2BoisVelhos;
    private javax.swing.JTextField m2Garrotes;
    private javax.swing.JCheckBox opcaoConfinamento;
    private javax.swing.JCheckBox opcaoCriacaoDeAves;
    private javax.swing.JCheckBox opcaoLeite;
    private javax.swing.JCheckBox opcaoPlantacao;
    private javax.swing.JTextField periodo1A;
    private javax.swing.JTextField periodo1B;
    private javax.swing.JTextField periodo2A;
    private javax.swing.JTextField periodo2B;
    private javax.swing.JTextField periodo3A;
    private javax.swing.JTextField periodo3B;
    private javax.swing.JTextField periodo4A;
    private javax.swing.JTextField periodo4B;
    // End of variables declaration//GEN-END:variables

    public void preencherFazenda() {

        fazenda.setCod_fazenda(cod_fazenda);
        fazenda.setConfinamento_bovino(opcaoConfinamento.isSelected());
        fazenda.setCriacao_aves(opcaoCriacaoDeAves.isSelected());
        fazenda.setLeite(opcaoLeite.isSelected());
        fazenda.setPlantacao(opcaoPlantacao.isSelected());
        
    }

    public void consultaFazenda() throws SQLException {

        conexao conexao = new conexao();
        conexao.getConexao();
        String selectSQL = "SELECT * FROM fazenda A where a.cod_fazenda = " + cod_fazenda;

        Statement pstmtCon;
        pstmtCon = conexao.getConexao().createStatement();

        ResultSet rs = pstmtCon.executeQuery(selectSQL);

        while (rs.next()) {

            opcaoConfinamento.setSelected(rs.getBoolean("confinamento_bovinos"));
            opcaoLeite.setSelected(rs.getBoolean("leite"));
            opcaoCriacaoDeAves.setSelected(rs.getBoolean("criacao_aves"));
            opcaoPlantacao.setSelected(rs.getBoolean("plantacao"));
        }

        rs.close();
        pstmtCon.close();

    }

    public void preencherFazendaConfinamento() {

        fazendaConfinamento.setCod_fazenda(cod_fazenda);
        fazendaConfinamento.setBezerrosA(Integer.parseInt(bezerrosA.getText()));
        fazendaConfinamento.setBezerrosB(Integer.parseInt(bezerrosB.getText()));
        fazendaConfinamento.setGarrotesA(Integer.parseInt(garrotesA.getText()));
        fazendaConfinamento.setGarrotesB(Integer.parseInt(garrotesB.getText()));
        fazendaConfinamento.setBoisA(Integer.parseInt(boisA.getText()));
        fazendaConfinamento.setBoisB(Integer.parseInt(boisB.getText()));
        fazendaConfinamento.setBoisVelhosA(Integer.parseInt(boisVelhosA.getText()));
        fazendaConfinamento.setBoisVelhosB(Integer.parseInt(boisVelhosB.getText()));
        fazendaConfinamento.setKgDiaBezerros(Double.parseDouble(KgDiaBezerros.getText()));
        fazendaConfinamento.setKgDiaGarrotes(Double.parseDouble(KgDiaGarrotes.getText()));
        fazendaConfinamento.setKgDiaBois(Double.parseDouble(KgDiaBois.getText()));
        fazendaConfinamento.setKgDiaBoisVelhos(Double.parseDouble(KgDiaBoisVelhos.getText()));
        fazendaConfinamento.setM2Bezerros(Integer.parseInt(m2Bezerros.getText()));
        fazendaConfinamento.setM2Garrotes(Integer.parseInt(m2Garrotes.getText()));
        fazendaConfinamento.setM2Bois(Integer.parseInt(m2Bois.getText()));
        fazendaConfinamento.setM2BoisVelhos(Integer.parseInt(m2BoisVelhos.getText()));
        fazendaConfinamento.setPeriodo1A(Integer.parseInt(periodo1A.getText()));
        fazendaConfinamento.setPeriodo1B(Integer.parseInt(periodo1B.getText()));
        fazendaConfinamento.setPeriodo2A(Integer.parseInt(periodo2A.getText()));
        fazendaConfinamento.setPeriodo2B(Integer.parseInt(periodo2B.getText()));
        fazendaConfinamento.setPeriodo3A(Integer.parseInt(periodo3A.getText()));
        fazendaConfinamento.setPeriodo3B(Integer.parseInt(periodo3B.getText()));
        fazendaConfinamento.setPeriodo4A(Integer.parseInt(periodo4A.getText()));
        fazendaConfinamento.setPeriodo4B(Integer.parseInt(periodo4B.getText()));
        fazendaConfinamento.setAlimentacao1(Integer.parseInt(alimentacao1.getText()));
        fazendaConfinamento.setAlimentacao2(Integer.parseInt(alimentacao2.getText()));
        fazendaConfinamento.setAlimentacao3(Integer.parseInt(alimentacao3.getText()));
        fazendaConfinamento.setAlimentacao4(Integer.parseInt(alimentacao4.getText()));

    }

    public void consultaFazendaConfinamento() throws SQLException {

        conexao conexao = new conexao();
        conexao.getConexao();
        String selectSQL = "SELECT * FROM fazendaConfinamento A ";

        Statement pstmtCon;
        pstmtCon = conexao.getConexao().createStatement();

        ResultSet rs = pstmtCon.executeQuery(selectSQL);

        while (rs.next()) {

            bezerrosA.setText(rs.getString("bezerrosA"));
            bezerrosB.setText(rs.getString("bezerrosB"));
            garrotesA.setText(rs.getString("garrotesA"));
            garrotesB.setText(rs.getString("garrotesB"));
            boisA.setText(rs.getString("boisA"));
            boisB.setText(rs.getString("boisB"));
            boisVelhosA.setText(rs.getString("boisVelhosA"));
            boisVelhosB.setText(rs.getString("boisVelhosB"));

            periodo1A.setText(rs.getString("periodo1A"));
            periodo1B.setText(rs.getString("periodo1B"));
            periodo2A.setText(rs.getString("periodo2A"));
            periodo2B.setText(rs.getString("periodo2B"));
            periodo3A.setText(rs.getString("periodo3A"));
            periodo3B.setText(rs.getString("periodo3B"));
            periodo4A.setText(rs.getString("periodo4A"));
            periodo4B.setText(rs.getString("periodo4B"));

            KgDiaBezerros.setText(rs.getString("KgDiaBezerros"));
            KgDiaGarrotes.setText(rs.getString("KgDiaGarrotes"));
            KgDiaBois.setText(rs.getString("KgDiaBois"));
            KgDiaBoisVelhos.setText(rs.getString("KgDiaBoisVelhos"));

            alimentacao1.setText(rs.getString("alimentacao1"));
            alimentacao2.setText(rs.getString("alimentacao2"));
            alimentacao3.setText(rs.getString("alimentacao3"));
            alimentacao4.setText(rs.getString("alimentacao4"));

            m2Bezerros.setText(rs.getString("m2Bezerros"));
            m2Garrotes.setText(rs.getString("m2Garrotes"));
            m2Bois.setText(rs.getString("m2Bois"));;
            m2BoisVelhos.setText(rs.getString("m2BoisVelhos"));

        }

        rs.close();
        pstmtCon.close();

    }
}
